version: '3.1'

services:

    db:
        image: postgres
        container_name: db
        environment: 
            POSTGRES_PASSWORD: password
            POSTGRES_USER: jakob
        volumes:
            - ./containers/db:/docker-entrypoint-initdb.d
        ports: 
            - "5432:5432"
        restart:
            always

    metabase:
        image: metabase/metabase
        container_name: metabase
        depends_on: 
            - "db"
        ports:
            - "3000:3000"